This code will find the concentrations needed for each of a variety of potential formulations involving both whitening and retinol agents

In [1]:
import numpy as np


desired concentations in percent

In [2]:
c_tagra = 0.3

In [3]:
c_w = 0.05

desired volume in milliliters 

In [4]:
vol = 1.0

supplied concentrations in percent

In [5]:
#supplied active concentrations:
A = 0.7
B = 0.1

In [6]:
#base concentration in combination cream
C1 = 100 - A - B


In [7]:
#base concentation in whitener-only cream:
C2 = 100 - B

In [8]:
#base concentation in tagra-only cream:
C3 = 100 - A

In [9]:
#base concentraion in base-only vehicle:
C4 = 100

required volume of components in cream with desired concentration and volume

In [10]:
y_tagra = vol*c_tagra/100

In [11]:
y_w = vol*c_w/100

In [12]:
y_b = vol - y_tagra - y_w

define linear algebra problem

In [13]:
b = np.array([y_tagra, y_w, y_b, vol])

In [14]:
M = np.array([[A,0,A,0],[B,B,0,0],[C1,C2,C3,C4],[100,100,100,100]])

In [15]:
M = M/100

In [16]:
M

array([[0.007, 0.   , 0.007, 0.   ],
       [0.001, 0.001, 0.   , 0.   ],
       [0.992, 0.999, 0.993, 1.   ],
       [1.   , 1.   , 1.   , 1.   ]])

solve the linear algebra problem to find the amounts required

In [17]:
import scipy
from scipy import optimize

In [18]:
X = scipy.optimize.nnls(M,b)

Solution

In [19]:
X

(array([0.42857143, 0.07142857, 0.        , 0.5       ]),
 1.3057859914872294e-16)

In [20]:
y_tagra

0.003

In [21]:
y = np.round(X[0],1)

In [22]:
y

array([0.4, 0.1, 0. , 0.5])

In [23]:
b_actual = M@y

In [24]:
b_actual

array([2.800e-03, 5.000e-04, 9.967e-01, 1.000e+00])